### ISSUE TITLE
CLi is not using defaults and help system

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#770]
CLi is not using defaults:

yarn offix generate >

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:449:10)
    at Object.readFileSync (fs.js:359:35)
    at Object.exports.generate (/Users/wtrocki/Projects/sync/offix/packages/datastore/cli/dist/generate.js:8:25)
    at Object.handler (/Users/wtrocki/Projects/sync/offix/packages/datastore/cli/dist/index.js:18:29)
    at Object.runCommand (/Users/wtrocki/Projects/sync/offix/packages/datastore/cli/node_modules/yargs/build/lib/command.js:196:48)
```

We should also support positional parameters

**Comment by Eunovo** [comment]
@wtrocki  SInce I'm adding positional arguments, can I drop current named arguments?

**Comment by wtrocki** [comment]
ok
